/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_package = 2,
  anon_sym_SEMI = 3,
  anon_sym_module = 4,
  anon_sym_using = 5,
  anon_sym_as = 6,
  anon_sym_DOT = 7,
  anon_sym_COLON_COLON = 8,
  anon_sym_export = 9,
  anon_sym_constexpr = 10,
  anon_sym_extern = 11,
  anon_sym_kernel = 12,
  anon_sym_runtime = 13,
  anon_sym_fn = 14,
  anon_sym_struct = 15,
  anon_sym_enum = 16,
  anon_sym_trait = 17,
  anon_sym_impl = 18,
  anon_sym_slot = 19,
  anon_sym_fragment = 20,
  anon_sym_interceptor = 21,
  anon_sym_context = 22,
  anon_sym_meta = 23,
  anon_sym_constraint = 24,
  anon_sym_AT = 25,
  anon_sym_LBRACE = 26,
  anon_sym_RBRACE = 27,
  anon_sym_LPAREN = 28,
  anon_sym_RPAREN = 29,
  anon_sym_LBRACK = 30,
  anon_sym_RBRACK = 31,
  sym_number = 32,
  sym_string = 33,
  sym_operator = 34,
  sym_punctuation = 35,
  sym_line_comment = 36,
  sym_source_file = 37,
  sym_package_header = 38,
  sym_module_header = 39,
  sym_using_header = 40,
  sym_package_id = 41,
  sym_module_path = 42,
  sym_declaration = 43,
  sym_metadata_attachment = 44,
  sym_block = 45,
  sym_parenthesized = 46,
  sym_bracketed = 47,
  sym__fragment = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_package_id_repeat1 = 50,
  aux_sym_module_path_repeat1 = 51,
  aux_sym_declaration_repeat1 = 52,
  aux_sym_declaration_repeat2 = 53,
  aux_sym_block_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_package] = "package",
  [anon_sym_SEMI] = ";",
  [anon_sym_module] = "module",
  [anon_sym_using] = "using",
  [anon_sym_as] = "as",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_export] = "export",
  [anon_sym_constexpr] = "constexpr",
  [anon_sym_extern] = "extern",
  [anon_sym_kernel] = "kernel",
  [anon_sym_runtime] = "runtime",
  [anon_sym_fn] = "fn",
  [anon_sym_struct] = "struct",
  [anon_sym_enum] = "enum",
  [anon_sym_trait] = "trait",
  [anon_sym_impl] = "impl",
  [anon_sym_slot] = "slot",
  [anon_sym_fragment] = "fragment",
  [anon_sym_interceptor] = "interceptor",
  [anon_sym_context] = "context",
  [anon_sym_meta] = "meta",
  [anon_sym_constraint] = "constraint",
  [anon_sym_AT] = "@",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [sym_line_comment] = "line_comment",
  [sym_source_file] = "source_file",
  [sym_package_header] = "package_header",
  [sym_module_header] = "module_header",
  [sym_using_header] = "using_header",
  [sym_package_id] = "package_id",
  [sym_module_path] = "module_path",
  [sym_declaration] = "declaration",
  [sym_metadata_attachment] = "metadata_attachment",
  [sym_block] = "block",
  [sym_parenthesized] = "parenthesized",
  [sym_bracketed] = "bracketed",
  [sym__fragment] = "_fragment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_package_id_repeat1] = "package_id_repeat1",
  [aux_sym_module_path_repeat1] = "module_path_repeat1",
  [aux_sym_declaration_repeat1] = "declaration_repeat1",
  [aux_sym_declaration_repeat2] = "declaration_repeat2",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_using] = anon_sym_using,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_export] = anon_sym_export,
  [anon_sym_constexpr] = anon_sym_constexpr,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_kernel] = anon_sym_kernel,
  [anon_sym_runtime] = anon_sym_runtime,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_trait] = anon_sym_trait,
  [anon_sym_impl] = anon_sym_impl,
  [anon_sym_slot] = anon_sym_slot,
  [anon_sym_fragment] = anon_sym_fragment,
  [anon_sym_interceptor] = anon_sym_interceptor,
  [anon_sym_context] = anon_sym_context,
  [anon_sym_meta] = anon_sym_meta,
  [anon_sym_constraint] = anon_sym_constraint,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [sym_line_comment] = sym_line_comment,
  [sym_source_file] = sym_source_file,
  [sym_package_header] = sym_package_header,
  [sym_module_header] = sym_module_header,
  [sym_using_header] = sym_using_header,
  [sym_package_id] = sym_package_id,
  [sym_module_path] = sym_module_path,
  [sym_declaration] = sym_declaration,
  [sym_metadata_attachment] = sym_metadata_attachment,
  [sym_block] = sym_block,
  [sym_parenthesized] = sym_parenthesized,
  [sym_bracketed] = sym_bracketed,
  [sym__fragment] = sym__fragment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_package_id_repeat1] = aux_sym_package_id_repeat1,
  [aux_sym_module_path_repeat1] = aux_sym_module_path_repeat1,
  [aux_sym_declaration_repeat1] = aux_sym_declaration_repeat1,
  [aux_sym_declaration_repeat2] = aux_sym_declaration_repeat2,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_using] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_export] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_constexpr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_kernel] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_runtime] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trait] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_impl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_slot] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fragment] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_interceptor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_context] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_meta] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_constraint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_package_header] = {
    .visible = true,
    .named = true,
  },
  [sym_module_header] = {
    .visible = true,
    .named = true,
  },
  [sym_using_header] = {
    .visible = true,
    .named = true,
  },
  [sym_package_id] = {
    .visible = true,
    .named = true,
  },
  [sym_module_path] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_attachment] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized] = {
    .visible = true,
    .named = true,
  },
  [sym_bracketed] = {
    .visible = true,
    .named = true,
  },
  [sym__fragment] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_package_id_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_module_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_declaration_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_abi = 1,
  field_kind = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_abi] = "abi",
  [field_kind] = "kind",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_kind, 0},
  [1] =
    {field_abi, 0},
    {field_kind, 1},
  [3] =
    {field_kind, 1},
  [4] =
    {field_abi, 1},
    {field_kind, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 30,
  [38] = 23,
  [39] = 36,
  [40] = 31,
  [41] = 25,
  [42] = 28,
  [43] = 43,
  [44] = 5,
  [45] = 4,
  [46] = 46,
  [47] = 12,
  [48] = 15,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 49,
  [53] = 50,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '!', 28,
        '"', 3,
        '%', 28,
        '&', 30,
        '(', 17,
        ')', 18,
        '*', 28,
        '+', 28,
        ',', 33,
        '-', 32,
        '.', 12,
        '/', 26,
        ':', 35,
        ';', 10,
        '<', 27,
        '=', 32,
        '>', 29,
        '@', 14,
        '[', 19,
        ']', 20,
        '^', 28,
        '{', 15,
        '|', 31,
        '}', 16,
        '?', 25,
        '~', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 28,
        '"', 3,
        '%', 28,
        '&', 30,
        '(', 17,
        ')', 18,
        '*', 28,
        '+', 28,
        '-', 32,
        '.', 34,
        '/', 26,
        ':', 35,
        '<', 27,
        '=', 32,
        '>', 29,
        '[', 19,
        ']', 20,
        '^', 28,
        '{', 15,
        '|', 31,
        '}', 16,
        ',', 33,
        ';', 33,
        '?', 25,
        '~', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 28,
        '"', 3,
        '%', 28,
        '&', 30,
        '(', 17,
        '*', 28,
        '+', 28,
        ',', 33,
        '-', 32,
        '.', 34,
        '/', 26,
        ':', 35,
        ';', 10,
        '<', 27,
        '=', 32,
        '>', 29,
        '@', 14,
        '[', 19,
        '^', 28,
        '{', 15,
        '|', 31,
        '?', 25,
        '~', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == ';') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(13);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(3);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(25);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '>') ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '&' ||
          lookahead == '=') ADVANCE(25);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=' ||
          lookahead == '|') ADVANCE(25);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '=' ||
          lookahead == '>') ADVANCE(25);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '.') ADVANCE(25);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == ':') ADVANCE(25);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'c', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'k', 6,
        'm', 7,
        'p', 8,
        'r', 9,
        's', 10,
        't', 11,
        'u', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(15);
      if (lookahead == 'x') ADVANCE(16);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == 'm') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(26);
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(29);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(32);
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'p') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(39);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(46);
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 31:
      if (lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 32:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 34:
      if (lookahead == 'g') ADVANCE(51);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 37:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 38:
      if (lookahead == 'a') ADVANCE(55);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(56);
      END_STATE();
    case 40:
      if (lookahead == 'k') ADVANCE(57);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(58);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(60);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 45:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(66);
      END_STATE();
    case 51:
      if (lookahead == 'm') ADVANCE(67);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_impl);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(68);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_meta);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(70);
      END_STATE();
    case 57:
      if (lookahead == 'a') ADVANCE(71);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_slot);
      END_STATE();
    case 60:
      if (lookahead == 'c') ADVANCE(73);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 62:
      if (lookahead == 'g') ADVANCE(75);
      END_STATE();
    case 63:
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead == 'r') ADVANCE(77);
      END_STATE();
    case 64:
      if (lookahead == 'x') ADVANCE(78);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(79);
      END_STATE();
    case 66:
      if (lookahead == 'n') ADVANCE(80);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 68:
      if (lookahead == 'c') ADVANCE(82);
      END_STATE();
    case 69:
      if (lookahead == 'l') ADVANCE(83);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 71:
      if (lookahead == 'g') ADVANCE(85);
      END_STATE();
    case 72:
      if (lookahead == 'm') ADVANCE(86);
      END_STATE();
    case 73:
      if (lookahead == 't') ADVANCE(87);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_trait);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_using);
      END_STATE();
    case 76:
      if (lookahead == 'x') ADVANCE(88);
      END_STATE();
    case 77:
      if (lookahead == 'a') ADVANCE(89);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(90);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_export);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_extern);
      END_STATE();
    case 81:
      if (lookahead == 'n') ADVANCE(91);
      END_STATE();
    case 82:
      if (lookahead == 'e') ADVANCE(92);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_kernel);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 85:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 86:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_struct);
      END_STATE();
    case 88:
      if (lookahead == 'p') ADVANCE(95);
      END_STATE();
    case 89:
      if (lookahead == 'i') ADVANCE(96);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_context);
      END_STATE();
    case 91:
      if (lookahead == 't') ADVANCE(97);
      END_STATE();
    case 92:
      if (lookahead == 'p') ADVANCE(98);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_package);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_runtime);
      END_STATE();
    case 95:
      if (lookahead == 'r') ADVANCE(99);
      END_STATE();
    case 96:
      if (lookahead == 'n') ADVANCE(100);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_fragment);
      END_STATE();
    case 98:
      if (lookahead == 't') ADVANCE(101);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_constexpr);
      END_STATE();
    case 100:
      if (lookahead == 't') ADVANCE(102);
      END_STATE();
    case 101:
      if (lookahead == 'o') ADVANCE(103);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_constraint);
      END_STATE();
    case 103:
      if (lookahead == 'r') ADVANCE(104);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_interceptor);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_using] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_export] = ACTIONS(1),
    [anon_sym_constexpr] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_kernel] = ACTIONS(1),
    [anon_sym_runtime] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_trait] = ACTIONS(1),
    [anon_sym_impl] = ACTIONS(1),
    [anon_sym_slot] = ACTIONS(1),
    [anon_sym_fragment] = ACTIONS(1),
    [anon_sym_interceptor] = ACTIONS(1),
    [anon_sym_context] = ACTIONS(1),
    [anon_sym_meta] = ACTIONS(1),
    [anon_sym_constraint] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(72),
    [sym_package_header] = STATE(2),
    [sym_module_header] = STATE(2),
    [sym_using_header] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_metadata_attachment] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_declaration_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_package] = ACTIONS(7),
    [anon_sym_module] = ACTIONS(9),
    [anon_sym_using] = ACTIONS(11),
    [anon_sym_export] = ACTIONS(13),
    [anon_sym_constexpr] = ACTIONS(13),
    [anon_sym_extern] = ACTIONS(13),
    [anon_sym_kernel] = ACTIONS(13),
    [anon_sym_runtime] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [anon_sym_struct] = ACTIONS(15),
    [anon_sym_enum] = ACTIONS(15),
    [anon_sym_trait] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(15),
    [anon_sym_slot] = ACTIONS(15),
    [anon_sym_fragment] = ACTIONS(15),
    [anon_sym_interceptor] = ACTIONS(15),
    [anon_sym_context] = ACTIONS(15),
    [anon_sym_meta] = ACTIONS(15),
    [anon_sym_constraint] = ACTIONS(15),
    [anon_sym_AT] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_package_header] = STATE(3),
    [sym_module_header] = STATE(3),
    [sym_using_header] = STATE(3),
    [sym_declaration] = STATE(3),
    [sym_metadata_attachment] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_declaration_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_package] = ACTIONS(7),
    [anon_sym_module] = ACTIONS(9),
    [anon_sym_using] = ACTIONS(11),
    [anon_sym_export] = ACTIONS(13),
    [anon_sym_constexpr] = ACTIONS(13),
    [anon_sym_extern] = ACTIONS(13),
    [anon_sym_kernel] = ACTIONS(13),
    [anon_sym_runtime] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [anon_sym_struct] = ACTIONS(15),
    [anon_sym_enum] = ACTIONS(15),
    [anon_sym_trait] = ACTIONS(15),
    [anon_sym_impl] = ACTIONS(15),
    [anon_sym_slot] = ACTIONS(15),
    [anon_sym_fragment] = ACTIONS(15),
    [anon_sym_interceptor] = ACTIONS(15),
    [anon_sym_context] = ACTIONS(15),
    [anon_sym_meta] = ACTIONS(15),
    [anon_sym_constraint] = ACTIONS(15),
    [anon_sym_AT] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_package_header] = STATE(3),
    [sym_module_header] = STATE(3),
    [sym_using_header] = STATE(3),
    [sym_declaration] = STATE(3),
    [sym_metadata_attachment] = STATE(20),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_declaration_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_package] = ACTIONS(25),
    [anon_sym_module] = ACTIONS(28),
    [anon_sym_using] = ACTIONS(31),
    [anon_sym_export] = ACTIONS(34),
    [anon_sym_constexpr] = ACTIONS(34),
    [anon_sym_extern] = ACTIONS(34),
    [anon_sym_kernel] = ACTIONS(34),
    [anon_sym_runtime] = ACTIONS(34),
    [anon_sym_fn] = ACTIONS(37),
    [anon_sym_struct] = ACTIONS(37),
    [anon_sym_enum] = ACTIONS(37),
    [anon_sym_trait] = ACTIONS(37),
    [anon_sym_impl] = ACTIONS(37),
    [anon_sym_slot] = ACTIONS(37),
    [anon_sym_fragment] = ACTIONS(37),
    [anon_sym_interceptor] = ACTIONS(37),
    [anon_sym_context] = ACTIONS(37),
    [anon_sym_meta] = ACTIONS(37),
    [anon_sym_constraint] = ACTIONS(37),
    [anon_sym_AT] = ACTIONS(40),
    [sym_string] = ACTIONS(43),
    [sym_line_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(48), 7,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_number,
      sym_string,
    ACTIONS(46), 19,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      sym_identifier,
      sym_operator,
      sym_punctuation,
  [34] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(52), 7,
      anon_sym_SEMI,
      anon_sym_AT,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_number,
      sym_string,
    ACTIONS(50), 19,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      sym_identifier,
      sym_operator,
      sym_punctuation,
  [68] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(54), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [96] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(56), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [124] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(58), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [152] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(60), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [180] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(62), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [208] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(64), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [236] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(66), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [264] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(68), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [292] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(70), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [320] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(72), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [348] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(74), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [376] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(76), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [404] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(78), 22,
      ts_builtin_sym_end,
      anon_sym_package,
      anon_sym_module,
      anon_sym_using,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [432] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(85), 1,
      anon_sym_AT,
    STATE(19), 2,
      sym_metadata_attachment,
      aux_sym_declaration_repeat1,
    ACTIONS(80), 5,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
    ACTIONS(83), 12,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      sym_string,
  [464] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_AT,
    ACTIONS(92), 1,
      sym_string,
    STATE(19), 2,
      sym_metadata_attachment,
      aux_sym_declaration_repeat1,
    ACTIONS(88), 5,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
    ACTIONS(90), 11,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
  [498] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(94), 18,
      anon_sym_export,
      anon_sym_constexpr,
      anon_sym_extern,
      anon_sym_kernel,
      anon_sym_runtime,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
      anon_sym_AT,
      sym_string,
  [522] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(104), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(96), 3,
      sym_identifier,
      sym_number,
      sym_string,
    ACTIONS(102), 3,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    STATE(22), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [556] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(123), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(113), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(25), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [588] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_SEMI,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    STATE(14), 1,
      sym_block,
    ACTIONS(135), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(125), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(43), 4,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_declaration_repeat2,
  [622] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    ACTIONS(141), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(137), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(22), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [654] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(143), 1,
      anon_sym_SEMI,
    STATE(17), 1,
      sym_block,
    ACTIONS(135), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(125), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(43), 4,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_declaration_repeat2,
  [688] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(147), 1,
      anon_sym_SEMI,
    STATE(18), 1,
      sym_block,
    ACTIONS(149), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(145), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(33), 4,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_declaration_repeat2,
  [722] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(151), 1,
      anon_sym_RBRACK,
    ACTIONS(141), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(137), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(22), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [754] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(155), 1,
      anon_sym_SEMI,
    STATE(8), 1,
      sym_block,
    ACTIONS(157), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(153), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(26), 4,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_declaration_repeat2,
  [788] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    ACTIONS(163), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(159), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(31), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [820] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    ACTIONS(141), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(137), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(22), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [852] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(169), 1,
      anon_sym_SEMI,
    STATE(9), 1,
      sym_block,
    ACTIONS(171), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(167), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(35), 4,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_declaration_repeat2,
  [886] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(173), 1,
      anon_sym_SEMI,
    STATE(7), 1,
      sym_block,
    ACTIONS(135), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(125), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(43), 4,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_declaration_repeat2,
  [920] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(177), 1,
      anon_sym_SEMI,
    STATE(13), 1,
      sym_block,
    ACTIONS(179), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(175), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(24), 4,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_declaration_repeat2,
  [954] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(181), 1,
      anon_sym_SEMI,
    STATE(16), 1,
      sym_block,
    ACTIONS(135), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(125), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(43), 4,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_declaration_repeat2,
  [988] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(185), 1,
      anon_sym_RBRACK,
    ACTIONS(187), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(183), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(28), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [1020] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    ACTIONS(193), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(189), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(40), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [1052] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    ACTIONS(199), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(195), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(41), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [1084] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(203), 1,
      anon_sym_RBRACK,
    ACTIONS(205), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(201), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(42), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [1116] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(207), 1,
      anon_sym_RBRACE,
    ACTIONS(141), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(137), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(22), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [1148] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
    ACTIONS(141), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(137), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(22), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [1180] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(211), 1,
      anon_sym_RBRACK,
    ACTIONS(141), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(137), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(22), 5,
      sym_block,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_block_repeat1,
  [1212] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
    ACTIONS(221), 1,
      anon_sym_LBRACK,
    ACTIONS(216), 2,
      anon_sym_SEMI,
      anon_sym_LBRACE,
    ACTIONS(224), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(213), 3,
      sym_identifier,
      sym_number,
      sym_string,
    STATE(43), 4,
      sym_parenthesized,
      sym_bracketed,
      sym__fragment,
      aux_sym_declaration_repeat2,
  [1241] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(50), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(52), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
      sym_string,
  [1260] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(46), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(48), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
      sym_string,
  [1279] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(227), 11,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
  [1296] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(229), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(66), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
      sym_string,
  [1315] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(231), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(72), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
      sym_string,
  [1334] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(235), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(233), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
      sym_string,
  [1353] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(239), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(237), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
      sym_string,
  [1372] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(241), 11,
      anon_sym_fn,
      anon_sym_struct,
      anon_sym_enum,
      anon_sym_trait,
      anon_sym_impl,
      anon_sym_slot,
      anon_sym_fragment,
      anon_sym_interceptor,
      anon_sym_context,
      anon_sym_meta,
      anon_sym_constraint,
  [1389] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(235), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(233), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
      sym_string,
  [1406] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(239), 2,
      sym_operator,
      sym_punctuation,
    ACTIONS(237), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
      sym_string,
  [1423] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(245), 1,
      anon_sym_DOT,
    STATE(55), 1,
      aux_sym_package_id_repeat1,
    ACTIONS(243), 2,
      anon_sym_SEMI,
      anon_sym_as,
  [1437] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(249), 1,
      anon_sym_DOT,
    STATE(55), 1,
      aux_sym_package_id_repeat1,
    ACTIONS(247), 2,
      anon_sym_SEMI,
      anon_sym_as,
  [1451] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(245), 1,
      anon_sym_DOT,
    STATE(54), 1,
      aux_sym_package_id_repeat1,
    ACTIONS(252), 2,
      anon_sym_SEMI,
      anon_sym_as,
  [1465] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(247), 3,
      anon_sym_SEMI,
      anon_sym_as,
      anon_sym_DOT,
  [1474] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(254), 1,
      anon_sym_SEMI,
    ACTIONS(256), 1,
      anon_sym_COLON_COLON,
    STATE(59), 1,
      aux_sym_module_path_repeat1,
  [1487] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(256), 1,
      anon_sym_COLON_COLON,
    ACTIONS(258), 1,
      anon_sym_SEMI,
    STATE(60), 1,
      aux_sym_module_path_repeat1,
  [1500] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(260), 1,
      anon_sym_SEMI,
    ACTIONS(262), 1,
      anon_sym_COLON_COLON,
    STATE(60), 1,
      aux_sym_module_path_repeat1,
  [1513] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(260), 2,
      anon_sym_SEMI,
      anon_sym_COLON_COLON,
  [1521] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(265), 1,
      sym_identifier,
    STATE(74), 1,
      sym_package_id,
  [1531] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(267), 1,
      sym_identifier,
    STATE(69), 1,
      sym_module_path,
  [1541] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(131), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_parenthesized,
  [1551] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(265), 1,
      sym_identifier,
    STATE(70), 1,
      sym_package_id,
  [1561] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(269), 1,
      anon_sym_SEMI,
  [1568] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(271), 1,
      sym_identifier,
  [1575] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(273), 1,
      sym_identifier,
  [1582] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(275), 1,
      anon_sym_SEMI,
  [1589] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(277), 1,
      anon_sym_as,
  [1596] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(279), 1,
      sym_identifier,
  [1603] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
  [1610] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(283), 1,
      sym_identifier,
  [1617] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(285), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 34,
  [SMALL_STATE(6)] = 68,
  [SMALL_STATE(7)] = 96,
  [SMALL_STATE(8)] = 124,
  [SMALL_STATE(9)] = 152,
  [SMALL_STATE(10)] = 180,
  [SMALL_STATE(11)] = 208,
  [SMALL_STATE(12)] = 236,
  [SMALL_STATE(13)] = 264,
  [SMALL_STATE(14)] = 292,
  [SMALL_STATE(15)] = 320,
  [SMALL_STATE(16)] = 348,
  [SMALL_STATE(17)] = 376,
  [SMALL_STATE(18)] = 404,
  [SMALL_STATE(19)] = 432,
  [SMALL_STATE(20)] = 464,
  [SMALL_STATE(21)] = 498,
  [SMALL_STATE(22)] = 522,
  [SMALL_STATE(23)] = 556,
  [SMALL_STATE(24)] = 588,
  [SMALL_STATE(25)] = 622,
  [SMALL_STATE(26)] = 654,
  [SMALL_STATE(27)] = 688,
  [SMALL_STATE(28)] = 722,
  [SMALL_STATE(29)] = 754,
  [SMALL_STATE(30)] = 788,
  [SMALL_STATE(31)] = 820,
  [SMALL_STATE(32)] = 852,
  [SMALL_STATE(33)] = 886,
  [SMALL_STATE(34)] = 920,
  [SMALL_STATE(35)] = 954,
  [SMALL_STATE(36)] = 988,
  [SMALL_STATE(37)] = 1020,
  [SMALL_STATE(38)] = 1052,
  [SMALL_STATE(39)] = 1084,
  [SMALL_STATE(40)] = 1116,
  [SMALL_STATE(41)] = 1148,
  [SMALL_STATE(42)] = 1180,
  [SMALL_STATE(43)] = 1212,
  [SMALL_STATE(44)] = 1241,
  [SMALL_STATE(45)] = 1260,
  [SMALL_STATE(46)] = 1279,
  [SMALL_STATE(47)] = 1296,
  [SMALL_STATE(48)] = 1315,
  [SMALL_STATE(49)] = 1334,
  [SMALL_STATE(50)] = 1353,
  [SMALL_STATE(51)] = 1372,
  [SMALL_STATE(52)] = 1389,
  [SMALL_STATE(53)] = 1406,
  [SMALL_STATE(54)] = 1423,
  [SMALL_STATE(55)] = 1437,
  [SMALL_STATE(56)] = 1451,
  [SMALL_STATE(57)] = 1465,
  [SMALL_STATE(58)] = 1474,
  [SMALL_STATE(59)] = 1487,
  [SMALL_STATE(60)] = 1500,
  [SMALL_STATE(61)] = 1513,
  [SMALL_STATE(62)] = 1521,
  [SMALL_STATE(63)] = 1531,
  [SMALL_STATE(64)] = 1541,
  [SMALL_STATE(65)] = 1551,
  [SMALL_STATE(66)] = 1561,
  [SMALL_STATE(67)] = 1568,
  [SMALL_STATE(68)] = 1575,
  [SMALL_STATE(69)] = 1582,
  [SMALL_STATE(70)] = 1589,
  [SMALL_STATE(71)] = 1596,
  [SMALL_STATE(72)] = 1603,
  [SMALL_STATE(73)] = 1610,
  [SMALL_STATE(74)] = 1617,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_using_header, 5, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 5, 0, 4),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 3),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 2),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_header, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_header, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 2),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, 0, 4),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata_attachment, 3, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(43),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_declaration_repeat2, 2, 0, 0),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(23),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(36),
  [224] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(43),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracketed, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracketed, 3, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracketed, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracketed, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_id, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_package_id_repeat1, 2, 0, 0),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_package_id_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_id, 1, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_path, 1, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_path, 2, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_path_repeat1, 2, 0, 0),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_path_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [281] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_luna(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "luna",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
